version: '3'

services:
  app:
    image: golang:1.20
    working_dir: /usr/src/app
    environment:
      - DB=/data/data.db
      - CGO_ENABLED=1
    volumes:
      - ./:/usr/src/app
      - ./.data:/data
      - deps:/go
      - cache:/root/.cache/go-build
  test_app:
    image: golang:1.20
    working_dir: /usr/src/app
    environment:
      - DB=/data/test.db
      - CGO_ENABLED=1
    volumes:
      - ./:/usr/src/app
      - ./.data:/data
      - deps:/go
      - cache:/root/.cache/go-build
  sqlite:
    image: keinos/sqlite3:3.42.0
    working_dir: /data
    volumes:
      - ./.data:/data


volumes:
  deps:
  cache:
