// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/goblinlordx/go-test/accounting"
	"github.com/goblinlordx/go-test/currency"
)

// Injectors from wire.go:

func InitializeApp() App {
	currencyRepository := currency.ProvideCurrencyRepository()
	accountRepository := accounting.ProvideAccountRepository()
	categoryRepository := accounting.ProvideCategoryRepository()
	transactionRepository := accounting.ProvideTransactionRepository()
	accountFilterer := accounting.ProvideAccountFilterer(currencyRepository)
	accountCommander := accounting.ProvideAccountCommander(accountRepository, transactionRepository, currencyRepository)
	transactionCommander := accounting.ProvideTransactionCommander(transactionRepository)
	app := ProvideApp(currencyRepository, accountRepository, categoryRepository, transactionRepository, accountFilterer, accountCommander, transactionCommander)
	return app
}
